yet more tests being made aware about really-static modules
run/t5125.scala
  The check file listed instance methods, which are not static.
Solution: update check file.

files/jvm/patmat_opt_ignore_underscore
  Ye Old Inliner can't parse a statified classfiles, complaining with:
    error: Illegal index: 0 overlaps List((variable par1,DOUBLE))
    locals: Map(1 -> List((variable par1,DOUBLE)))
Solution:
--update-check after .flags to -neo:o1 . The .check file contains a listing of bytecode instructions, which thanks to -neo:o1 is different from what used to be