letting tests go of their assumptions about non-really-static modules
Ye old inliner can't inline static methods, and with statitification the target of the callsite below is static:
    INVOKESTATIC scala/Predef$ArrowAssoc$.$minus$greater$extension (Ljava/lang/Object;Ljava/lang/Object;)Lscala/Tuple2;
which is reported by flags "-optimise -Xfatal-warnings" of files/pos/t3420.scala
That callsite is emitted for
    val cv = Map[Int, Int](1 -> 2)
Solution: in the flags file, replace -optimise with -neo:o3

Ye old inliner fails to parse bytecode it needs to -optimise pos/t4579.scala, complaining with:
    error: Illegal index: 0 overlaps List((variable par1,DOUBLE))
    locals: Map(1 -> List((variable par1,DOUBLE)))

run/optimizer-array-load.scala
  Again Ye Old Inliner can't handle the library compiled with statification
Solution: -neo:o3 instead of -optimise

run/inline-ex-handlers.scala
  To print the ICode that the test compares against the .check file, GenASM has to be used, which as we've seen doesn't know about statification, thus the bytecode it emits fails to run (against the std library compiled by GenBCode)

run/dead-code-elimination.scala
Solution: -neo:o1

run/t3569.scala
Solution: -neo:o3

files/run/t4935.scala
files/jvm/patmat_opt_no_nullcheck
The .flags file should be update to use -neo:o3