another round of tests that don't come to terms with really-static modules
run/t7008-scala-defined
The problem here is that t7008-scala-defined/ScalaClassWithCheckedExceptions_1.scala can only be compiled with GenASM, because GenBCode (correctly) complains that:
  An AbstractTypeSymbol (SI-7122) has reached the bytecode emitter, for which no JVM-level internal name can be found: ScalaClassWithCheckedExceptions_1.E1
because there's really no class ScalaClassWithCheckedExceptions_1.E1 , look:
  class ScalaClassWithCheckedExceptions_1[E1 <: Exception] @throws[NullPointerException]("") () {
    @throws[E1]("") def bar() {}
    @throws[IllegalStateException]("") def baz(x: Int) {}
    // FIXME: SI-7066
    // @throws[E2]("") def foo[E2 <: Exception] {}
  }
Now, after GenASM compiles the above, it fails at runtime, because GenASM doesn't "statify" as GenBCode does, and thus emits INVOKEVIRTUAL where INVOKESTATIC should have been emitted:
    java.lang.IncompatibleClassChangeError: Expecting non-static method scala.compat.Platform$.EOL()Ljava/lang/String;
            at Macros$.impl(Impls_Macros_2.scala:7)

run/t5789.scala
  The test consists of a ReplTest subclass with the overrides:
    override def extraSettings = "-Yinline"
  As a result GenASM runs, which emits an invokevirtual (unaware of statification) which results in:
  The code emitted under statification includes:
    java.lang.IncompatibleClassChangeError: Expecting non-static method scala.runtime.ScalaRunTime$.replStringOf(Ljava/lang/Object;I)Ljava/lang/String;
Solution: the override in the test's Test class should read:
  override def extraSettings = "-neo:o2"